package com.ramosa.lab_7;

import org.springframework.stereotype.Service;
import java.util.List;
import java.util.Optional;

@Service
public class ProductService {

    private final ProductRepository productRepository;

    public ProductService(ProductRepository productRepository) {
        this.productRepository = productRepository;
    }

    public List<Product> getAllProducts() {
        return productRepository.findAll();
    }

    public Product getProductById(Long id) {
        return productRepository.findById(id).orElse(null);
    }

    public Product addProduct(Product product) {
        // ID is auto-generated by database
        return productRepository.save(product);
    }

    public Product updateProduct(Long id, Product updatedDetails) {
        Optional<Product> existing = productRepository.findById(id);
        if (existing.isPresent()) {
            Product product = existing.get();
            product.setName(updatedDetails.getName());
            product.setPrice(updatedDetails.getPrice());
            return productRepository.save(product);
        }
        return null; // Product not found
    }

    public void deleteProduct(Long id) {
        productRepository.deleteById(id);
    }
}